title: David Bindel
email: bindel@cornell.edu
description: Course Page for CS 5220
baseurl: ""
url: "http://cornell-cs5220-f15.github.io/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
