title: CS 5220
description: Course Page for CS 5220
author: David Bindel
email: bindel@cornell.edu
baseurl: "/"
url: "http://cornell-cs5220-f15.github.io/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
